#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=48g,walltime=0:45:00
#PBS -N app-AFQ_figures
#PBS -V

set -e

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

echo "mapping measures to cortical surface"
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:7.1.1 ./map-fmri-to-cortex.sh
